### ISSUE TITLE
Download all rivers from wikidata

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/wikidata-water-features#1]
Wikidata has lots information about rivers. For example: https://www.wikidata.org/wiki/Q3411

We want to download all rivers, based on the (instance of, river) statement. The output should be a delimited file, something like:

```
Mackenzie River,Q3411
Grand River,Q1542855
...
```

In theory, we should just be able to query the SPARQL endpoint: https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/Wikidata_Query_Help

The right query should be something like:

```
SELECT ?item ?itemLabel 
WHERE 
{
  ?item wdt:P31 wd:Q4022.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```

However, for me, the query doesn't finish... I get "Server error: Unexpected end of JSON input" with partial results.

If the query service doesn't work, we might need to parse out what we need from the raw JSON dumps.

**Comment by Govind9** [comment]
I have added the script and data with 6e1491905a6f98cd4d6727d0dd2cd74f4efec9ee
