### ISSUE TITLE
Build spaCy module for detecting rivers

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/wikidata-water-features#2]
Guide here: https://spacy.io/usage/rule-based-matching

In particular, we should make use of the phrase matcher: https://spacy.io/api/phrasematcher
Which says:

> The `PhraseMatcher` lets you efficiently match large terminology lists.

... which is basically what we have...

**Comment by Govind9** [comment]
Here 9213aeb101ad9e388d41ca42d03055ed8e908fc5 

- Added a class that can be used to search for rivers against any given text.
- Class by default loads all the rivers in the csv from Wikidata.
- Other rivers can also be added to the vocabulary.
- The results are rendered easily using `spaCy`.
- Added notebook for module walkthrough
- Many false matches are seen due to river names like "Is", "One", etc.

**Comment by lintool** [comment]
Good.

> Many false matches are seen due to river names like "Is", "One", etc.

To address this issue, implement a simple rule: Rivers are proper names and should have initial caps.

Also, ignore all caps, like "ERA" - these are abbreviations.

**Comment by lintool** [comment]
```
        for match in matches:
            for m in re.finditer(match, text):
                entities[0]["ents"].append({
                    "start": m.start(), "end": m.end(), "label": "RIVER", "title": None
                })
```

I assume spaCy will allow us to append custom attributes? In which case, we should add in the link to the Wikidata entity? For example, the Volga River is Q626.

**Comment by Govind9** [comment]
> Good.
> 
> > Many false matches are seen due to river names like "Is", "One", etc.
> 
> To address this issue, implement a simple rule: Rivers are proper names and should have initial caps.
> 
> Also, ignore all caps, like "ERA" - these are abbreviations.

Here d917e84a79223e3fc717ec838cf900d7e9d89e43 included these rules.

**Comment by Govind9** [comment]
This is not allowed by spaCy.
> ```
>         for match in matches:
>             for m in re.finditer(match, text):
>                 entities[0]["ents"].append({
>                     "start": m.start(), "end": m.end(), "label": "RIVER", "title": None
>                 })
> ```
> 
> I assume spaCy will allow us to append custom attributes? In which case, we should add in the link to the Wikidata entity? For example, the Volga River is Q626.

The `HydroMatch::match()` function already returns a list of matches found in the text, we can add the hyperlinks of each match to this list.

**Comment by lintool** [comment]
What about `Span.set_extension`? https://spacy.io/api/span
See https://spacy.io/usage/processing-pipelines#custom-components-attributes
Search for "Example: Pipeline component for GPE entities and country meta data via a REST API".

**Comment by Govind9** [comment]
Yes professor, including this in the module.
> What about `Span.set_extension`? https://spacy.io/api/span
> See https://spacy.io/usage/processing-pipelines#custom-components-attributes
> Search for "Example: Pipeline component for GPE entities and country meta data via a REST API".

**Comment by Govind9** [comment]
Here 60d92cae0627aa82565d742a3592d5d97eb52595 The wikilinks are added as part of the doc being returned with matches for the given text.
Test Run At:
https://colab.research.google.com/drive/1rMqc_8s6uA1mcavHOsclX5m0urci5ad5
