### ISSUE TITLE
Download all lakes from wikidata

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/wikidata-water-features#3]
Similar to #1 - let's do the same for lakes, and then add to #2

**Comment by Govind9** [comment]
Total number of `lakes`: 249315 
Number of `lakes` with `area`: 49931

**Comment by lintool** [comment]
Yea, let's just grab those with areas.

**Comment by Govind9** [comment]
Here 694771c7acf632436c9c2021a71b8a23ac46e0a9 lake data has been downloaded. 
One thing to consider here is that the majority of the lakes (after filtering by area) don't have a name i.e. their name field is just their ID. Out of a total 49931 lakes with area only 5875 have a name.
Ignoring the area filter, out of a total 249323 lakes, 168949 have names.

**Comment by lintool** [comment]
We should only retain lakes that have actual names and areas then.
