### ISSUE TITLE
Rule to throw out rivers with common names

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/wikidata-water-features#4]
"Is the Nile River very long?" will currently extract "Is" as a river since it's the name of a river and it is capitalized.

Simple solution is to disallow rivers comprising common English words to stand alone.
Let's use this list: https://simple.wiktionary.org/wiki/Wiktionary:Most_frequent_1000_words_in_English

So, a common word is only recognized if it explicitly says "river". So "Is" (no matter capitalization) by itself is never recognized, but "Is river" (or "Is River" or "IS River") will be.

Note this will still allow un-common English words to denote rivers alone, e.g., "The Nile is long." will be fine since Nile is not a common English word.

**Comment by Govind9** [comment]
Here c7471f4f992f4c14ffeb480bddfcd2df00e58507 I have added this rule as well. Example run can be seen at: https://colab.research.google.com/drive/1rMqc_8s6uA1mcavHOsclX5m0urci5ad5
