### ISSUE TITLE
"Lake Belwood" is thrown out!

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/wikidata-water-features#6]
from the current detector because it doesn't have an area: https://www.wikidata.org/wiki/Q6474952

Perhaps we can think of a different way of filtering... how about keep every feature that has a Wikipedia page?

**Comment by Govind9** [comment]
Number lakes with "English" wikipedia pages is 11535.
Number of lakes with area and proper name is 5875 (currently used).

**Comment by Govind9** [comment]
Here 5496fe067c928190db751b13e8b5433e7db5dd01
Lakes with wikipedia pages in any language are included. Number of lakes included: 79724
"Lake Belwood" and "Conestoga Lake" being recognized now.

**Comment by lintool** [comment]
Great, thanks!
